### ISSUE TITLE
Yo, need support pls!

### ISSUE THREAD

**Issue by binhoz** [Shipow/hexabones#3]
bower sass-twitter-bootstrap#\*            EHTTP Status code of 404

others bower dependencies's outdated.. ;( 
someone can help me!?

**Comment by Shipow** [comment]
started to fix the build :+1: 
https://github.com/Shipow/hexabones/commit/58b235d6285908bca8881389c8ba74bac8e2ee67

**Comment by binhoz** [comment]
Yoo!! morning, thanks bro!
